#!/bin/sh -e 
# 
# Dynamically change font size in rxvt. 
# 
# Tweak this with your own font settings 
#
# AUTOR: Val
# WWW: https://www.codejam.info/2014/09/change-rxvt-font-size-on-the-fly.html
# DATE September 18, 2014

readonly PREFIX='xft:monospace:size=' 

if
 	[ -z "$1" ]; then     
	echo 'Usage: fz <size>' 
    	exit 1
fi

printf '\33]50;%s%d\007' "$PREFIX" "$1"
